# this exists as an example of how the wrangler.toml config needs to look with redacted variables
name = "prole"
type = "javascript"

compatibility_date = "2021-12-29"
workers_dev = true

kv-namespaces = [
  { binding = "USERS", id = "REDACTED", preview_id = "REDACTED" }
]

[vars]
FAUNA_SECRET = "REDACTED"
SEND_GRID_SECRET = "REDACTED"
HELP_EMAIL = "REDACTED"

[env.production]
zone_id = "REDACTED"
account_id = "REDACTED"
route = "REDACTED"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
